### ISSUE TITLE
Integrate to GlassFish

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-ha-api#14]
Integrate to Eclipse GlassFish

**Comment by vinayvishal** [comment]
Just an update: Changes are in place for this task. However, there are constant failure in Quicklook (16 of these tests are failing) if new version is integrated with Glassfish. I am currently trying to debug those post which I will be submitting the PR.

**Comment by vinayvishal** [comment]
The issue got resolved and CI tests passed post the fix in #16 .
