### ISSUE TITLE
Remove runsAsUser from Jenkinsfile

### ISSUE THREAD

**Issue by mbarbero** [eclipse-ee4j/glassfish-ha-api#26]
In the `Jenkinsfile`, you are referencing the user id `1000100000 ` at https://github.com/eclipse-ee4j/glassfish-ha-api/blob/master/Jenkinsfile#L39. It does not need to be there and is actually preventing builds from starting (see various stuck builds at https://ci.eclipse.org/glassfish/job/ha-api/). You should just drop it like https://github.com/eclipse-ee4j/glassfish did.

**Comment by arjantijms** [comment]
You're right Mikaël. Apologies for the stuck builds this project caused.
